/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main_WordRain */

#ifndef _Included_Main_WordRain
#define _Included_Main_WordRain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main_WordRain
 * Method:    rainWord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_00024WordRain_rainWord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
